"""
Report Generator Module
Creates professional PDF reports using FPDF2 (Windows-compatible)
"""

import os
from datetime import datetime
from typing import Dict, List, Optional
from fpdf import FPDF
from pathlib import Path
import textwrap


class TrendSpotterPDF(FPDF):
    """Custom PDF class with professional styling"""
    
    def __init__(self):
        super().__init__()
        self.primary_color = (46, 134, 171)    # Blue
        self.secondary_color = (162, 59, 114)  # Purple
        self.success_color = (40, 167, 69)     # Green
        self.warning_color = (255, 193, 7)     # Yellow
        self.danger_color = (220, 53, 69)      # Red
        self.dark_color = (52, 58, 64)         # Dark gray
        
    def header(self):
        """Custom header for each page"""
        # Only show on pages after the first
        if self.page_no() > 1:
            self.set_font('Helvetica', 'I', 9)
            self.set_text_color(*self.dark_color)
            self.cell(0, 10, 'TrendSpotter Report', 0, 0, 'L')
            self.cell(0, 10, f'Page {self.page_no()}', 0, 1, 'R')
            self.ln(5)
    
    def footer(self):
        """Custom footer for each page"""
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by TrendSpotter - {datetime.now().strftime("%Y-%m-%d")}', 0, 0, 'C')


class ReportGenerator:
    """
    Generates professional PDF reports from data and AI insights
    Uses FPDF2 for Windows compatibility
    """
    
    def __init__(self, template_dir: str = 'templates', output_dir: str = 'output'):
        """
        Initialize the report generator
        
        Args:
            template_dir: Directory containing templates (not used with FPDF)
            output_dir: Directory for output files
        """
        self.template_dir = template_dir
        self.output_dir = output_dir
        
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(template_dir, exist_ok=True)
    
    def generate_report(self, data: Dict, output_filename: str = None) -> str:
        """
        Generate a PDF report from the provided data
        
        Args:
            data: Dictionary containing all report data
            output_filename: Name for the output file (without extension)
            
        Returns:
            Path to the generated PDF file
        """
        # Set default filename
        if output_filename is None:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_filename = f'performance_report_{timestamp}'
        
        # Create PDF
        pdf = TrendSpotterPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Add first page
        pdf.add_page()
        
        # Add header section
        self._add_header_section(pdf, data)
        
        # Add KPI cards
        self._add_kpi_section(pdf, data.get('kpis'))
        
        # Add executive summary
        self._add_executive_summary(pdf, data.get('executive_summary', ''))
        
        # Add anomaly alerts
        if data.get('anomalies'):
            self._add_anomaly_section(pdf, data['anomalies'], data.get('anomaly_analysis', ''))
        
        # New page for charts
        pdf.add_page()
        
        # Add charts
        self._add_charts_section(pdf, data.get('charts', {}))
        
        # Add campaign table
        if data.get('campaign_data'):
            pdf.add_page()
            self._add_campaign_table(pdf, data['campaign_data'])
        
        # Add recommendations
        if data.get('recommendations'):
            self._add_recommendations(pdf, data['recommendations'])
        
        # Save PDF
        pdf_path = os.path.join(self.output_dir, f'{output_filename}.pdf')
        pdf.output(pdf_path)
        
        print(f"✅ PDF Report generated: {pdf_path}")
        return pdf_path
    
    def _add_header_section(self, pdf: TrendSpotterPDF, data: Dict):
        """Add the header section with title and date"""
        # Background rectangle
        pdf.set_fill_color(*pdf.primary_color)
        pdf.rect(0, 0, 210, 50, 'F')
        
        # Title
        pdf.set_font('Helvetica', 'B', 26)
        pdf.set_text_color(255, 255, 255)
        pdf.set_xy(15, 12)
        pdf.cell(0, 10, data.get('title', 'Weekly Performance Report'), 0, 1)
        
        # Subtitle
        pdf.set_font('Helvetica', '', 14)
        pdf.set_xy(15, 24)
        pdf.cell(0, 10, data.get('subtitle', 'Automated AdTech Analytics'), 0, 1)
        
        # Date
        pdf.set_font('Helvetica', '', 11)
        pdf.set_xy(15, 36)
        report_date = datetime.now().strftime('%B %d, %Y at %H:%M')
        pdf.cell(0, 10, f'Report Generated: {report_date}', 0, 1)
        
        pdf.ln(15)
    
    def _add_kpi_section(self, pdf: TrendSpotterPDF, kpis):
        """Add KPI cards section"""
        pdf.set_y(60)
        
        # Section title
        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(*pdf.primary_color)
        pdf.cell(0, 10, 'Key Performance Indicators', 0, 1)
        
        # Draw underline
        pdf.set_draw_color(*pdf.primary_color)
        pdf.set_line_width(0.5)
        pdf.line(10, pdf.get_y(), 100, pdf.get_y())
        pdf.ln(8)
        
        if not kpis:
            return
        
        # KPI grid (3 columns, 2 rows)
        kpi_data = [
            ('Total Impressions', f'{kpis.total_impressions:,}', pdf.success_color),
            ('Total Clicks', f'{kpis.total_clicks:,}', pdf.primary_color),
            ('Total Conversions', f'{kpis.total_conversions:,}', pdf.primary_color),
            ('Total Revenue', f'${kpis.total_revenue:,.0f}', pdf.success_color),
            ('Total Spend', f'${kpis.total_spend:,.0f}', pdf.warning_color),
            ('Overall ROI', f'{kpis.roi:.1f}%', pdf.success_color if kpis.roi > 100 else pdf.warning_color),
        ]
        
        start_x = 15
        start_y = pdf.get_y()
        card_width = 58
        card_height = 25
        margin = 4
        
        for i, (label, value, color) in enumerate(kpi_data):
            col = i % 3
            row = i // 3
            
            x = start_x + col * (card_width + margin)
            y = start_y + row * (card_height + margin)
            
            # Card background
            pdf.set_fill_color(248, 249, 250)
            pdf.rect(x, y, card_width, card_height, 'F')
            
            # Left border
            pdf.set_fill_color(*color)
            pdf.rect(x, y, 2, card_height, 'F')
            
            # Label
            pdf.set_font('Helvetica', '', 8)
            pdf.set_text_color(108, 117, 125)
            pdf.set_xy(x + 5, y + 3)
            pdf.cell(card_width - 10, 5, label.upper(), 0, 0)
            
            # Value
            pdf.set_font('Helvetica', 'B', 16)
            pdf.set_text_color(*pdf.dark_color)
            pdf.set_xy(x + 5, y + 10)
            pdf.cell(card_width - 10, 10, value, 0, 0)
        
        pdf.set_y(start_y + 2 * (card_height + margin) + 10)
    
    def _add_executive_summary(self, pdf: TrendSpotterPDF, summary: str):
        """Add executive summary section"""
        pdf.ln(5)
        
        # Section title
        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(*pdf.primary_color)
        pdf.cell(0, 10, 'Executive Summary', 0, 1)
        
        # Draw underline
        pdf.set_draw_color(*pdf.primary_color)
        pdf.line(10, pdf.get_y(), 100, pdf.get_y())
        pdf.ln(8)
        
        # AI badge
        pdf.set_fill_color(46, 134, 171)
        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_text_color(255, 255, 255)
        pdf.set_xy(15, pdf.get_y())
        pdf.cell(45, 6, 'AI-Generated Analysis', 0, 1, 'C', fill=True)
        pdf.ln(5)
        
        # Summary text
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(*pdf.dark_color)
        
        # Clean and wrap text
        if summary:
            # Remove markdown formatting
            clean_text = summary.replace('**', '').replace('##', '').replace('# ', '')
            
            # Split into paragraphs
            paragraphs = clean_text.split('\n\n')
            
            for para in paragraphs:
                para = para.strip()
                if para:
                    # Handle bullet points
                    if para.startswith('- ') or para.startswith('* '):
                        para = '  - ' + para[2:]
                    
                    pdf.multi_cell(0, 5, para)
                    pdf.ln(3)
    
    def _add_anomaly_section(self, pdf: TrendSpotterPDF, anomalies: List[Dict], analysis: str):
        """Add anomaly alerts section"""
        # Check if we need a new page
        if pdf.get_y() > 200:
            pdf.add_page()
        
        pdf.ln(5)
        
        # Section title
        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(*pdf.primary_color)
        pdf.cell(0, 10, 'Anomaly Alerts', 0, 1)
        
        # Draw underline
        pdf.set_draw_color(*pdf.primary_color)
        pdf.line(10, pdf.get_y(), 100, pdf.get_y())
        pdf.ln(8)
        
        # Summary text
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(*pdf.dark_color)
        pdf.cell(0, 5, f'{len(anomalies)} anomalies detected during the reporting period:', 0, 1)
        pdf.ln(5)
        
        # Display top 5 anomalies
        for i, anomaly in enumerate(anomalies[:5]):
            severity = anomaly.get('severity', 'medium')
            
            # Set color based on severity
            if severity == 'high':
                color = pdf.danger_color
            elif severity == 'medium':
                color = pdf.warning_color
            else:
                color = (23, 162, 184)  # Info color
            
            # Alert box
            y_start = pdf.get_y()
            if severity == 'high':
                pdf.set_fill_color(255, 245, 245)
            else:
                pdf.set_fill_color(255, 253, 245)
            pdf.rect(15, y_start, 180, 18, 'F')
            
            # Left border
            pdf.set_fill_color(*color)
            pdf.rect(15, y_start, 3, 18, 'F')
            
            # Campaign name and metric
            pdf.set_xy(22, y_start + 2)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.set_text_color(*pdf.dark_color)
            campaign = anomaly.get('campaign_name', 'Unknown')
            metric = anomaly.get('metric', '').replace('_', ' ').title()
            pdf.cell(100, 5, f'{campaign} - {metric}', 0, 0)
            
            # Severity badge
            pdf.set_xy(165, y_start + 2)
            pdf.set_fill_color(*color)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font('Helvetica', 'B', 8)
            pdf.cell(25, 5, severity.upper(), 0, 0, 'C', fill=True)
            
            # Description
            pdf.set_xy(22, y_start + 9)
            pdf.set_font('Helvetica', '', 9)
            pdf.set_text_color(73, 80, 87)
            desc = anomaly.get('description', '')[:80]
            pdf.cell(170, 5, desc, 0, 0)
            
            pdf.set_y(y_start + 22)
    
    def _add_charts_section(self, pdf: TrendSpotterPDF, charts: Dict):
        """Add charts section"""
        # Section title
        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(*pdf.primary_color)
        pdf.cell(0, 10, 'Performance Visualizations', 0, 1)
        
        # Draw underline
        pdf.set_draw_color(*pdf.primary_color)
        pdf.line(10, pdf.get_y(), 120, pdf.get_y())
        pdf.ln(10)
        
        # Add charts if available
        chart_keys = ['dashboard', 'impressions_trend', 'revenue_by_campaign', 
                      'platform_performance', 'anomaly_chart']
        
        chart_added = False
        for key in chart_keys:
            chart_path = charts.get(key)
            if chart_path and os.path.exists(chart_path):
                try:
                    # Check if we need a new page
                    if pdf.get_y() > 180:
                        pdf.add_page()
                    
                    # Add chart image
                    pdf.image(chart_path, x=15, y=pdf.get_y(), w=180)
                    pdf.ln(90)  # Approximate height of chart
                    chart_added = True
                except Exception as e:
                    print(f"   Warning: Could not add chart {key}: {e}")
        
        if not chart_added:
            pdf.set_font('Helvetica', 'I', 10)
            pdf.set_text_color(128, 128, 128)
            pdf.cell(0, 10, 'Charts not available - see output/charts folder', 0, 1)
    
    def _add_campaign_table(self, pdf: TrendSpotterPDF, campaign_data: List[Dict]):
        """Add campaign performance table"""
        # Section title
        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(*pdf.primary_color)
        pdf.cell(0, 10, 'Campaign Performance Summary', 0, 1)
        
        # Draw underline
        pdf.set_draw_color(*pdf.primary_color)
        pdf.line(10, pdf.get_y(), 130, pdf.get_y())
        pdf.ln(8)
        
        # Table header
        pdf.set_fill_color(*pdf.primary_color)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 9)
        
        col_widths = [45, 30, 25, 20, 30, 25]
        headers = ['Campaign', 'Impressions', 'Clicks', 'CTR', 'Revenue', 'ROI']
        
        x_start = 15
        for i, (header, width) in enumerate(zip(headers, col_widths)):
            pdf.set_xy(x_start + sum(col_widths[:i]), pdf.get_y())
            pdf.cell(width, 8, header, 1, 0, 'C', fill=True)
        pdf.ln()
        
        # Table rows
        pdf.set_text_color(*pdf.dark_color)
        pdf.set_font('Helvetica', '', 9)
        
        for j, campaign in enumerate(campaign_data[:10]):  # Limit to 10 rows
            # Alternate row colors
            if j % 2 == 0:
                pdf.set_fill_color(248, 249, 250)
            else:
                pdf.set_fill_color(255, 255, 255)
            
            row_data = [
                campaign.get('name', '')[:18],
                f"{campaign.get('impressions', 0):,}",
                f"{campaign.get('clicks', 0):,}",
                f"{campaign.get('ctr', 0):.2f}%",
                f"${campaign.get('revenue', 0):,.0f}",
                f"{campaign.get('roi', 0):.1f}%"
            ]
            
            for i, (data, width) in enumerate(zip(row_data, col_widths)):
                pdf.set_xy(x_start + sum(col_widths[:i]), pdf.get_y())
                align = 'C' if i > 0 else 'L'
                pdf.cell(width, 7, data, 1, 0, align, fill=True)
            pdf.ln()
    
    def _add_recommendations(self, pdf: TrendSpotterPDF, recommendations: List[str]):
        """Add recommendations section"""
        # Check if we need a new page
        if pdf.get_y() > 220:
            pdf.add_page()
        
        pdf.ln(10)
        
        # Section title
        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(*pdf.primary_color)
        pdf.cell(0, 10, 'Recommendations', 0, 1)
        
        # Draw underline
        pdf.set_draw_color(*pdf.primary_color)
        pdf.line(10, pdf.get_y(), 80, pdf.get_y())
        pdf.ln(8)
        
        # Recommendations list
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(*pdf.dark_color)
        
        for i, rec in enumerate(recommendations[:5], 1):
            # Background
            y_start = pdf.get_y()
            pdf.set_fill_color(248, 249, 250)
            pdf.rect(15, y_start, 180, 12, 'F')
            
            # Arrow
            pdf.set_xy(18, y_start + 3)
            pdf.set_text_color(*pdf.primary_color)
            pdf.set_font('Helvetica', 'B', 12)
            pdf.cell(8, 6, '>', 0, 0)
            
            # Text
            pdf.set_xy(28, y_start + 3)
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(*pdf.dark_color)
            pdf.multi_cell(160, 5, rec[:100])
            
            pdf.set_y(y_start + 15)


class KPIData:
    """Data class for KPI metrics"""
    def __init__(self, total_impressions=0, total_clicks=0, total_conversions=0,
                 total_revenue=0, total_spend=0, roi=0, ctr=0, conversion_rate=0):
        self.total_impressions = total_impressions
        self.total_clicks = total_clicks
        self.total_conversions = total_conversions
        self.total_revenue = total_revenue
        self.total_spend = total_spend
        self.roi = roi
        self.ctr = ctr
        self.conversion_rate = conversion_rate


if __name__ == "__main__":
    # Test the module
    generator = ReportGenerator()
    
    # Create test data
    test_data = {
        'title': 'Weekly Performance Report',
        'subtitle': 'November 1-14, 2025',
        'kpis': KPIData(
            total_impressions=9500000,
            total_clicks=285000,
            total_conversions=14250,
            total_revenue=412500,
            total_spend=165000,
            roi=150.0,
            ctr=3.0,
            conversion_rate=5.0
        ),
        'executive_summary': '''Performance Overview

This week showed strong overall performance across all campaigns. Total revenue reached $412,500, representing a 150% ROI on ad spend.

Key Highlights:
- Impressions increased by 15% week-over-week
- Tech_Gadgets campaign achieved highest revenue at $85,000
- Miami region showed concerning 40% traffic drop on Nov 3rd

Recommendations:
- Investigate Miami traffic anomaly
- Scale up Tech_Gadgets campaign budget by 20%
- A/B test new creatives for Winter_Collection
''',
        'anomalies': [
            {
                'campaign_name': 'Tech_Gadgets',
                'metric': 'impressions',
                'severity': 'high',
                'description': 'Impressions dropped 72% below average on Nov 3rd in Miami'
            },
            {
                'campaign_name': 'Winter_Collection',
                'metric': 'clicks',
                'severity': 'medium',
                'description': 'CTR declined 35% on Nov 7th in Chicago'
            }
        ],
        'campaign_data': [
            {'name': 'Tech_Gadgets', 'impressions': 2100000, 'clicks': 63000, 'ctr': 3.0, 'revenue': 85000, 'roi': 180},
            {'name': 'Holiday_Promo', 'impressions': 1900000, 'clicks': 57000, 'ctr': 3.0, 'revenue': 75000, 'roi': 165},
            {'name': 'Black_Friday_Sale', 'impressions': 1800000, 'clicks': 54000, 'ctr': 3.0, 'revenue': 72000, 'roi': 155},
        ],
        'recommendations': [
            'Increase budget for Tech_Gadgets campaign by 20%',
            'Investigate Miami traffic drop - check for ad serving issues',
            'Run A/B tests on Winter_Collection creative assets',
            'Consider expanding to new platforms for underperforming campaigns'
        ]
    }
    
    pdf_path = generator.generate_report(test_data, 'test_report')
    print(f"\nReport saved to: {pdf_path}")
